project:
  type: website
  output-dir: docs
  lib-dir: library
  render:
    - "*.qmd"
    - "!lectures/"
  resources:
    - "files/"
    - "images/"
    - "lectures/*.html"
    - "lectures/*.scss"
    - "lectures/*.css"
    - "lectures/*_files/"
    - "lectures/libs/"
    - "lectures/*.png"
    - "bib/*.csl"
    - "bib/*.bib"

website:
  title: "US Foreign Policy"
  description: "Course page for POLSC 343 US Foreign Policy"
  navbar:
    background: "#512888"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Instructor
      - text: "Syllabus"
        menu:
          - href: syllabus-f2025.qmd
            text: "Syllabus"
          - href: syllabus-boilerplate-stuff.qmd
            text: "University Syllabus Statements"
      - text: "Archives"
        menu:
          - href: syllabi-archive.qmd
            text: Syllabi Archive
          - href: lectures.qmd
            text: Lecture Archive
          - href: https://www.youtube.com/channel/UC7AzCLAufJAMCKkDL77clzw
            text: YouTube Channel
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: source

execute:
  freeze: auto
