---
title: "US Foreign Policy"
description: "POLSC 343 Course Page"
---

Welcome, this page will serve as the homepage for POLSC 343 US foreign policy.

## Course Summary
 
Does politics really stop at the water's edge? Why does the US use military force, and when? Do voters really not care about foreign policy? What tools does the US use to advance its foreign policy goals? And who determines those goals? This semester we'll try to tackle all of these questions, and more, as we develop a better understanding of US foreign policy, its causes, and its consequences.

While it can seem removed from our every day lives, foreign policy has an enormous impact on how we experience the world. From the booming sounds of Ft. Riley to the prices we pay at the grocery store, foreign policy is, in fact, a very local thing! And while we'll be focuses on "big" issues concerning the US and how it relates to the world, we'll also try to make connections between those big issues and more local concerns to help students appreciate the impact of foreign policy on their everyday lives.

Our goal is to ultimately develop a better understanding of the actors, institutions, interests, and issues that have defined US foreign policy since the 1700s. To that end, this course begins with a general historical overview of US foreign policy since the 1700s. We then move into a discussion of the central actors and institutions that affect foreign policymaking. Finally, we transition to a focus on selected topics in US foreign policy, including the use of military force, security cooperation, trade, monetary policy, and more.  


## Course Objectives

1. The overarching goal is to develop an understanding of the actors, institutions, interests, and issues and systematic forces that shape US foreign policymaking. Please note that this is different than prescribing what policy should be (though this is also an important consideration when considering our motivations for studying the topic and reading course materials).
2. Identify the key actors that influence foreign policy.
3. Understand how and when the influence of actors varies (e.g. across time, issue area, etc.).
4. Identify the key issues confronting policymakers and society. 
5. Identify general trends in US foreign policy over time. 
    - What's changed? 
    - What stays the same?
    - When and why do we see changes in behavior or policies?
6. Students should develop a familiarity with social science research processes, practices. Specifically, students should have:
    - A basic understanding of how to read social scientific research articles. 
    - A basic understanding of research design considerations
    - A basic understanding of the scope and limitations of research articles
    
If you have any additional questions please don't hesitate to ask! Thanks!
