---
title: "Lectures"
---

This pages contains links to the various lecture slides used throughout the semester. You will also be able to find lectures in the archive.

This page contains lectures delivered throughout the semester. You can click on the links below to access the slides. Additional information can be found on my [YouTube Channel](https://www.youtube.com/channel/UC7AzCLAufJAMCKkDL77clzw). Please note that I don't update these video versions regularly, so there may be a disconnect between what you find below and the video content on the channel.

## Lecture Slides

1. [Course Introduction](lectures/introduction.html)

2. [Methods Primer](lectures/methods-primer.html)

3. [Historical Background](lectures/historical-background.html)

4. [The Cold War in International Affairs](lectures/cold-war-international.html)

5. [The Cold War in Domestic Politics](lectures/cold-war-domestic.html)

6. [The Policymaking Process](lectures/policymaking.html)

7. [Congress and the Presidency](lectures/congress-and-presidency.html)

8. [Bureaucracy and the State Department](lectures/bureaucracy.html)

9. [The Defense Department and the Military](lectures/defense-military.html)

10. [The Use of Military Force](lectures/military-force.html)

11. [Security Cooperation](lectures/security-cooperation.html)

12. [Trade and Investment](lectures/trade-investment.html)

13. [Foreign Aid](lectures/foreign-aid.html)

14. [Human Rights](lectures/human-rights.html)

15. [Multilateralism](lectures/multilateralism.html)

16. [Environmental Policy](lectures/environmental-policy.html)
